version: "3.7"

services:
  mariadb:
    image: mariadb
    container_name: userCenterDB
    restart: always
    volumes:
      - /DB/my_maria/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: backend_user
    ports:
      - 3306:3306
    networks:
     - backendCenter

  goserver:
    image: golang
    container_name: golangServer
    ports:
      - 8080:8080
    restart: always
    volumes:
       - .:/server
    depends_on:
      - mariadb
    working_dir: /server
    entrypoint: go run main.go
    networks:
     - backendCenter


networks:
    backendCenter:
      external: true 